version: 2.1

executors:
  docker-builder:
    machine:
      docker_layer_caching: true
    environment:
      SWIFTLINT_REVISION: "0.25.1"
      SWIFT_VERSION: "4.1"

workflows:
  build_deploy:
    jobs:
      - build
      - deploy:
          requires: [build]
          filters:
            branches:
              only:
                - master

jobs:
  build:
    executor: docker-builder
    steps:
      - checkout
      - run: make build
      - run: docker run endocrimes/swiftlint:${SWIFTLINT_REVISION} help

  deploy:
    executor: docker-builder
    steps:
      - checkout
      - run: make build
      - run: docker run endocrimes/swiftlint:${SWIFTLINT_REVISION} help
      - run: docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
      - run: make release
